version: 5.0.{build}
image: Visual Studio 2019
skip_tags: true
branches:
  only:
    - master
configuration: Release
nuget:
  account_feed: true
  project_feed: true
before_build:
  - ps: >-
      nuget restore

build:
  project: OpenXmlPowerTools.sln
  publish_aspnet_core: true
  verbosity: minimal

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}-prerelease"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

artifacts:
  - path: '**\OpenXmlPowerTools.*.nupkg'