version: 5.0.{build}
image:
  - Visual Studio 2022
  - Ubuntu
skip_tags: true
configuration: Release

before_build:
  - ps: dotnet restore

build:
  project: OpenXmlPowerTools.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

deploy:
  - provider: NuGet
    api_key:
      secure: CTISdGCfnpyC7Rh5vs1pgbuISrkWF34sot0SyVgvu0HQxhNNd+V0Gc4MS+rtJttB
    skip_symbols: false
    on:
      branch: main
  - provider: GitHub
    auth_token:
      secure: i84Zdoc7+IZkxfCY4245FM30wZLJGuOomoYsogC0WBxJMKT1Mob1dD/oqbFMFaut
    on:
      branch: main
